---
- name: Check if nvm is installed
  stat:
    path: /home/ec2-user/.nvm
  register: nvm_installed

- name: Install nvm
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
    dest: /home/ec2-user/install_nvm.sh
    mode: 'u+rwx,g+rx,o+rx'
  when: not nvm_installed.stat.exists

- name: Run nvm installation script
  command: /bin/bash /home/ec2-user/install_nvm.sh
  args:
    creates: /home/ec2-user/.nvm

- name: Load nvm script
  shell: |
    export NVM_DIR="/home/ec2-user/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This Loads nvm
  args:
    executable: /bin/bash

- name: Check if Node.js is installed
  command: "nvm list | grep -q '{{ node_version }}'"
  register: node_installed
  ignore_errors: yes

- name: Install Node.js 
  command: "nvm install {{ node_version }}"
  when: node_installed is failed