---
# - name: Ensure log directory is writable
#   file:
#     path: "/var/www{{ app_directory }}/log"
#     state: directory
#     mode: 0775
#     owner: ec2-user
#     group: ec2-user

# - name: Ensure development.log is writable
#   file:
#     path: "/var/www{{ app_directory }}/log/development.log"
#     state: touch
#     mode: 0664
#     owner: ec2-user
#     group: ec2-user

# - name: Ensure tmp/miniprofiler directory is writable
#   file:
#     path: "/var/www{{ app_directory }}/tmp/miniprofiler"
#     state: directory
#     mode: 0775
#     owner: ec2-user
#     group: ec2-user

- name: Install necessary gems
  become: no
  shell: |
    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$HOME/.gem/ruby/3.2.3/bin:$PATH"
    bundle install
  args:
    chdir: "/var/www{{ app_directory }}"
    executable: /bin/bash

# - name: Fix permissions for /var/www{{ app_directory }}/tmp
#   file:
#     path: "/var/www{{ app_directory }}/tmp"
#     owner: ec2-user
#     group: ec2-user
#     mode: 0755

# - name: Fix permissions for /var/www/raisetech-live8-sample-app/db/schema.rb
#   file:
#     path: /var/www/raisetech-live8-sample-app/db/schema.rb
#     owner: ec2-user
#     group: ec2-user
#     mode: 0644

- name: Run application setup script 
  shell: |
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    source ~/.bash_profile
    bin/setup
  args:
    chdir: "/var/www{{ app_directory }}"
    executable: /bin/bash
  become_user: ec2-user

# - name: Ensure correct permissions on yarn.lock
#   file:
#     path: "/var/www{{ app_directory }}/yarn.lock"
#     owner: ec2-user
#     group: ec2-user
#     mode: 0644

- name: Update caniuse-lite database  
  command: /home/ec2-user/.nvm/versions/node/v17.9.1/bin/npx update-browserslist-db@latest
  args:
    chdir: "/var/www{{ app_directory }}"
  become_user: ec2-user
  async: 1200  # 最大20分間実行可能
  poll: 0  # 非同期タスクとして実行
  register: update_task

- name: Wait for caniuse-lite database update to finish
  async_status:
    jid: "{{ update_task.ansible_job_id }}"
  become_user: ec2-user
  register: job_result
  until: job_result.finished
  retries: 30
  delay: 60

# - name: Set permissions for application.css
#   file:
#     path: "/var/www{{ app_directory }}/app/assets/builds/application.css"
#     owner: ec2-user
#     group: ec2-user
#     mode: 0664

- name: Precompile application assets  
  shell: |
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    export PATH="$HOME/.rbenv/shims:$PATH"
    source ~/.bash_profile
    rails assets:precompile
  args:
    chdir: "/var/www{{ app_directory }}"
    executable: /bin/bash
  become_user: ec2-user