---
- name: Ensure log directory is writable
  file:
    path: "/var/www{{ app_directory }}/log"
    state: directory
    mode: '0775'
    owner: ec2-user
    group: ec2-user

- name: Ensure development.log is writable
  file:
    path: "/var/www{{ app_directory }}/log/development.log"
    state: touch
    mode: '0664'
    owner: ec2-user
    group: ec2-user

- name: Ensure tmp/miniprofiler directory is writable
  file:
    path: "/var/www{{ app_directory }}/tmp/miniprofiler"
    state: directory
    mode: '0775'
    owner: ec2-user
    group: ec2-user

- name: Ensure Gemfile is readable
  file:
    path: "/var/www{{ app_directory }}/Gemfile"
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Ensure Gemfile.lock is readable
  file:
    path: "/var/www{{ app_directory }}/Gemfile.lock"
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Ensure Bundler path is in ec2-user's PATH
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/.bash_profile
    regexp: '^(export PATH=.*)'
    line: 'export PATH=$PATH:/home/ec2-user/.gem/ruby/3.2.3/bin'
    create: yes

- name: Install necessary gems
  become_user: ec2-user
  command: bundle install
  args:
    chdir: "/var/www{{ app_directory }}"

- name: Run application setup script
  shell: bash -lc "bin/setup"
  args:
    chdir: "/var/www{{ app_directory }}"

- name: Precompile application assets  
  shell: bash -lc "rails assets:precompile"
  args:
    chdir: "/var/www{{ app_directory }}"