---
- name: Check if rbenv is installed
  become: no
  stat:
    path: /home/ec2-user/.rbenv
  register: rbenv_installed

- name: Install rbenv
  become: no
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: not rbenv_installed.stat.exists

- name: Configure PATH for rbenv
  become: no
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: not rbenv_installed.stat.exists

- name: Initialize rbenv
  become: no
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
  when: not rbenv_installed.stat.exists

- name: Reload shell
  become: no
  shell: source /home/ec2-user/.bash_profile  # "exec $SHELL --login"の代わり
  args:
    executable: /bin/bash
  when: not rbenv_installed.stat.exists

- name: Check if ruby-build is installed
  become: no
  stat:
    path: /home/ec2-user/.rbenv/plugins/ruby-build
  register: ruby_build_installed

- name: Install ruby-build  # rbenv プラグインとして ruby-build をインストール
  become: no
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: not ruby_build_installed.stat.exists

- name: Install Ruby
  become: no
  shell: /home/ec2-user/.rbenv/bin/rbenv install {{ ruby_version }}
  args:
    creates: /home/ec2-user/.rbenv/versions/{{ ruby_version }}

- name: Set global Ruby version
  become: no
  shell: /home/ec2-user/.rbenv/bin/rbenv global {{ ruby_version }}