---
- name: Check if rbenv is installed
  stat:
    path: /home/ec2-user/.rbenv
  register: rbenv_installed

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: not rbenv_installed.stat.exists

- name: Configure PATH for rbenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: not rbenv_installed.stat.exists

- name: Initialize rbenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
  when: not rbenv_installed.stat.exists

- name: Reload shell
  command: "exec $SHELL --login"
  when: not rbenv_installed.stat.exists

- name: Check if ruby-build is installed
  stat:
    path: /home/ec2-user/.rbenv/plugins/ruby-build
  register: ruby_build_installed

- name: Install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: not ruby_build_installed.stat.exists

- name: Install Ruby
  shell: /home/ec2-user/.rbenv/bin/rbenv install {{ ruby_version }}
  args:
    creates: /home/ec2-user/.rbenv/versions/{{ ruby_version }}

- name: Set global Ruby version
  shell: /home/ec2-user/.rbenv/bin/rbenv global {{ ruby_version }}
