---
- name: Copy puma.service to systemd directory
  copy:
    src: files/puma.service.sample  # ファイルの相対パス
    dest: /etc/systemd/system/puma.service

- name: Ensure puma directory exists
  file:
    path: "/var/www{{ app_directory }}/tmp/sockets"
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Create puma configuration file
  template:
    src: templates/puma.rb.j2
    dest: "/var/www{{ app_directory }}/config/puma.rb"
    owner: ec2-user
    group: ec2-user

- name: Reload systemd manually
  command: systemctl daemon-reload

- name: Start and enable puma service
  systemd:
    name: puma
    state: started
    enabled: yes
