AWSTemplateFormatVersion: 2010-09-09
Description: rds template 

Parameters:
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10 

# --------------    
# Resources
# --------------
Resources: 

# ---------------------
# RDS Subnet Group
# ---------------------
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: subnet group for rds
      DBSubnetGroupName: !Sub "${NameBase}-sbnGroup"
      SubnetIds: 
        - !ImportValue PrivateSubnet1a
        - !ImportValue PrivateSubnet1c 
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-sbnGroup"

# -----------------
# RDS Instance  
# -----------------
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: "" 
      DBInstanceIdentifier: !Sub "${NameBase}-db"
      DBSubnetGroupName: !Ref RDSSubnetGroup
      Engine: mysql
      EngineVersion: 8.0.33
      LicenseModel: general-public-license
      MasterUsername: admin
      MasterUserPassword: 
        Fn::Sub: '{{resolve:secretsmanager:lec10-rds-jsonSecrets:SecretString:RDSUserPassword}}'
      MultiAZ: false
      Port: 3306
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue SecGroupRDS
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-rds"