AWSTemplateFormatVersion: 2010-09-09
Description: vpc template 

Parameters:
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10

# --------------    
# Resources
# --------------
Resources: 

# --------
# VPC
# --------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-vpc"

# ---------------------
# Internet Gateway
# ---------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-igw"

# -----------------------
# Gateway Attachment 
# -----------------------
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

# -------------------
# Public Subnets     
# -------------------
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select: 
        - 0
        - Fn::GetAZs: ""
      VpcId: !Ref VPC
      CidrBlock: 172.16.0.0/24
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-public-subnet-1a"

  PublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select: 
        - 1
        - Fn::GetAZs: ""
      VpcId: !Ref VPC
      CidrBlock: 172.16.1.0/24
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-public-subnet-1c"

# --------------------
# Private Subnets  
# --------------------
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
        - 0
        - Fn::GetAZs: ""
      VpcId: !Ref VPC
      CidrBlock: 172.16.2.0/24
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-private-subnet-1a"
  
  PrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
        - 1
        - Fn::GetAZs: ""
      VpcId: !Ref VPC
      CidrBlock: 172.16.3.0/24
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-private-subnet-1c"

# -----------------------
# Public Route Table
# -----------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-public-routetable"

# -------------------
# Public Routing 
# -------------------
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0  #localhost 向けルーティングは省く
      GatewayId: !Ref InternetGateway

# ------------------------ 
# Private Route Table
# ------------------------  
  PrivateRouteTable1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-private-routetable-1a"

  PrivateRouteTable1c:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-private-routetable-1c"

# ----------------------------
# Route Table Association   
# ----------------------------
  PublicRouteAssoc1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable

  PublicRouteAssoc1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1c
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteAssoc1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1a
      RouteTableId: !Ref PrivateRouteTable1a

  PrivateRouteAssoc1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1c
      RouteTableId: !Ref PrivateRouteTable1c

# ------------
# Outputs
# ------------ 
Outputs:
  VPC:
    Value: !Ref VPC
    Export: 
      Name: VPC

  PublicSubnet1a:
    Value: !Ref PublicSubnet1a
    Export: 
      Name: PublicSubnet1a

  PublicSubnet1c:
    Value: !Ref PublicSubnet1c
    Export: 
      Name: PublicSubnet1c

  PrivateSubnet1a:
    Value: !Ref PrivateSubnet1a
    Export: 
      Name: PrivateSubnet1a

  PrivateSubnet1c:
    Value: !Ref PrivateSubnet1c
    Export: 
      Name: PrivateSubnet1c