version: 2.1
orbs:
  python: circleci/python@2.0.3
  # aws-cli: circleci/aws-cli@4.1.1
  # ansible: orbss/ansible-playbook@0.0.5
  # ruby: circleci/ruby@2.1.0

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  # execute-cfn:
  #   executor: aws-cli/default
  #   steps:
  #     - checkout
  #     - aws-cli/setup:
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #         aws-region: AWS_DEFAULT_REGION
  #     - run: 
  #         name: deploy CloudFormation
  #         command: |
  #             set -x
  #             aws cloudformation deploy --template-file cloudformation/VPC_lec10.yml --stack-name lecture10-VPC
  #             aws cloudformation deploy --template-file cloudformation/SecuriyGroup_lec10.yml --stack-name lecture10-SecurityGroup
  #             aws cloudformation deploy --template-file cloudformation/EC2_lec10.yml --stack-name lecture10-EC2 --capabilities CAPABILITY_IAM
  #             aws cloudformation deploy --template-file cloudformation/ALB_lec10.yml --stack-name lecture10-ALB
  #             aws cloudformation deploy --template-file cloudformation/RDS_lec10.yml --stack-name lecture10-RDS
  #             aws cloudformation deploy --template-file cloudformation/S3_lec10.yml --stack-name lecture10-S3

  # execute-ansible:
  #   executor: ansible-playbook/default
  #   steps:
  #     - checkout
  #     - ansible-playbook/install:
  #         version: 2.10.7
  #     - add_ssh_keys:
  #         fingerprints:
  #           - ""
  #     - ansible-playbook/playbook:
  #         playbook: ansible/playbook.yml
  #         playbook-options: '-i anisble/inventory'

  # execute-serverspec:
  #   executor: ruby/default
  #   steps:
  #     - checkout
  #     - ruby/install:
  #         version: '3.1.2'
  #     - ruby/install-deps:
  #         app-dir: serverspec

workflows:
  raisetech:
    jobs:
      - cfn-lint
      # - execute-cfn:
      #     requires:
      #       - cfn-lint
      # - execute-ansible:
      #     requires:
      #       - execute-cfn
      # - execute-serverspec:
      #     requires:
      #       - execute-ansible