---
- name: Check if yarn is installed
  become: no
  command: yarn --version
  register: yarn_installed
  ignore_errors: yes

- name: Install yarn
  become: no
  shell: |
    export NVM_DIR="/home/ec2-user/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install -g yarn
  when: yarn_installed is failed
  args:
    executable: /bin/bash
