---
- name: Remove mariadb-libs
  yum:
    name: mariadb-libs
    state: absent

- name: Check if MySQL 8.0 community release RPM is installed
  command:
    cmd: rpm -q mysql84-community-release-el7-1
  register: mysql_rpm_check 
  failed_when: false    #　失敗しても以降の処理を続行
  changed_when: false   #　どの結果も変更があったとはみなさない

- name: Install MySQL 8.4 community release RPM
  command:
    cmd: yum localinstall -y https://dev.mysql.com/downloads/repo/yum/mysql84-community-release-el7-1.noarch.rpm
  register: mysql_rpm_installed
  when: mysql_rpm_check.rc != 0

- name: Disable MySQL 5.7 community repository
  command: yum-config-manager --disable mysql57-community
  when: mysql_rpm_installed.changed 

- name: Enable MySQL 8.0 community repository
  command: yum-config-manager --enable mysql80-community
  when: mysql_rpm_installed.changed 

- name: Refresh YUM cache
  command: yum makecache  # リポジトリの情報を最新の状態に
  when: mysql_rpm_installed.changed  

- name: install mysql-community-client
  yum:
    name: mysql-community-client
    state: present

- name: Install MySQL development tools
  yum:
    name: mysql-community-devel
    state: present

- name: Run application setup script
  become: no
  shell: bash -lc "bin/setup"
  args:
    chdir: "{{ app_directory }}"
  when: mysql_rpm_installed.changed

- name: Precompile application assets
  become: no
  shell: bash -lc "rails assets:precompile"
  args:
    chdir: "{{ app_directory }}"
  when: ansible_env.rails_env == 'production'  # 本番環境の時のみ