---
- name: Add rbenv shims to PATH
  become: no
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/shims:$PATH"'
    state: present

- name: Ensure Ruby environment is loaded
  become: no
  shell: source /home/ec2-user/.bash_profile && rbenv rehash
  args:
    executable: /bin/bash

- name: Check if Rails is installed
  become: no
  shell: bash -lc "gem list rails | grep -q '{{ rails_version }}'"
  register: rails_installed
  ignore_errors: yes

- name: Install Rails
  become: no
  shell: bash -lc "gem install rails -v '{{ rails_version }}'"
  when: rails_installed is failed