---
- name: Check if Rails is installed
  become: no
  shell: "gem list rails | grep -q '{{ rails_version }}'"
  register: rails_installed
  ignore_errors: yes

- name: Install Rails
  become: no
  command: "gem install rails -v '{{ rails_version }}'"
  when: rails_installed is failed