---
- name: Clone the GitHub repository
  become: no
  git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_directory }}"
    force: yes
  register: git_clone_action

- name: Ensure the directory ownership is ec2-user
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    recurse: yes
  when: git_clone_action.changed

- name: Copy configuration files
  become: no
  template:
    src: "{{ item.src }}"
    dest: "{{ app_directory }}/config/{{ item.dest }}"
  loop:
    - { src: 'database.yml.j2', dest: 'database.yml' }
    - { src: 'development.rb.j2', dest: 'environments/development.rb' }
    - { src: 'storage.yml.j2', dest: 'storage.yml' }
    - { src: 'unicorn.rb.j2', dest: 'unicorn.rb' }