---
- name: Check if Nginx is installed
  become: no
  shell: bash -lc "nginx -v"
  register: nginx_check
  changed_when: no
  ignore_errors: yes

- name: Install Nginx if not already installed
  shell: bash -lc "amazon-linux-extras install -y nginx1"
  when: nginx_check.rc != 0

- name: Ensure Nginx is running and enabled at boot
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy Nginx configuration file for Rails app
  template:
    src: rails.conf.j2
    dest: /etc/nginx/conf.d/rails.conf
    owner: root
    group: root
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    state: restarted