---
- name: Check if Nginx is installed
  become: no
  command: nginx -v
  register: nginx_check
  changed_when: false
  ignore_errors: yes

- name: Install Nginx if not already installed
  command: amazon-linux-extras install -y nginx1
  when: nginx_check.failed

- name: Copy Nginx configuration file for Rails app
  template:
    src: rails.conf.j2
    dest: /etc/nginx/conf.d/rails.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx

- name: Ensure Nginx is running and enabled at boot
  systemd:
    name: nginx
    state: started
    enabled: yes