AWSTemplateFormatVersion: 2010-09-09
Description: ec2 template 

Parameters:
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10 

# --------------    
# Resources
# --------------
Resources: 

# -------------
# Key Pair 
# -------------
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: EC2KeyPair
      KeyType: rsa

# -------------
# IAM Role
# -------------
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
           - arn:aws:iam::aws:policy/AmazonS3FullAccess

# -------------------------
# IAM Instance Profile
# -------------------------
  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref IAMRole

# -----------------
# EC2 Instance
# -----------------
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      DisableApiTermination: false
      ImageId: ami-09bad682e5ae72267
      NetworkInterfaces:
           - AssociatePublicIpAddress: true
             DeviceIndex: 0
             SubnetId: !ImportValue PublicSubnet1a
             GroupSet:
                  - !ImportValue SecGroupEC2
      InstanceType: t2.micro
      IamInstanceProfile: !Ref IAMInstanceProfile
      Monitoring: false
      AvailabilityZone: 
        Fn::Select: 
        - 0
        - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-ec2"

# ------------
# Outputs
# ------------ 
Outputs:
  EC2:
    Value: !Ref EC2
    Export: 
      Name: EC2