AWSTemplateFormatVersion: 2010-09-09
Description: s3 template 

Parameters:
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10 

# --------------    
# Resources
# --------------
Resources: 

# --------------
# S3 Bucket
# --------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private 
      BucketName: !Sub "${NameBase}-s3-s3bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-s3-s3bucket"

# ---------------------
# S3 Bucket Policy
# ---------------------
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: 
                - "arn:aws:iam::769879083332:role/lecture10-EC2-IAMRole-PUYI5QHW9ILR"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource: 
              - !Sub "arn:aws:s3:::${S3Bucket}/*"