---
- hosts: target_node
  become: yes
  roles:
    - role: yum
    - role: nvm
    - role: yarn
    - role: ruby
    - role: rails
    - role: bundler
    - role: app
    - role: mysql
    - role: setup
    - role: nginx