---
- hosts: target_node
  become: yes
  roles:
    # - { role: yum, tags: yum }
    # - { role: nvm, tags: nvm }
    # - { role: yarn, tags: yarn }
    - { role: ruby, tags: ruby }
    - { role: rails, tags: rails }
    # - { role: bundler, tags: bundler }
    # - { role: app, tags: app }
    - { role: mysql, tags: mysql }
    # - { role: nginx, tags: nginx }   