---
- name: Check if Bundler is installed
  become: no
  shell: |
    export PATH="$HOME/.rbenv/shims:$PATH"
    bundler -v | grep {{ bundler_version }}
  register: bundler_check
  changed_when: no
  ignore_errors: yes

- name: Install Bundler
  become: no
  gem:
    name: bundler
    version: "{{ bundler_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: bundler_check is failed
